### ISSUE TITLE
defaultLocal is selected but not loaded

### ISSUE THREAD

**Issue by Olithom** [lgalfaso/angular-dynamic-locale#58]
Hello, sorry for my english.

I use 
tmhDynamicLocaleProvider.defaultLocale('en-us');
tmhDynamicLocaleProvider.useCookieStorage();

If the file corresponding to the cookie does not exist, tmhDynamicLocale broadcast an error $localeChangeError and set $locale.id and activeLocale variable to defaultLocale.

When I try to set with the defaultLocal on this error, as (localeId === activeLocale), then the file is not requested.

It is possible I have not understand the fallback mecanism.

**Comment by lgalfaso** [comment]
Hi, if you can create a plunker that shows the error, then it would be ideal.

Just a note, in Angular there is a clear separation between configuration and runtime. You should never change the configuration once your application start. In this case, you should not set the default once your application started and you receive the error.

**Comment by Olithom** [comment]
Thank for your answer !

I have create the plunker : http://plnkr.co/edit/vOc4D32tXpFHKeP6r5yO?p=preview

When you are a new user or click on 'simule en-us' and click stop/run, the response is
en-us
myEnglishTest 

When you click on 'simule missing language and click stop/run, the response is
en-us but there is not any value.

**Comment by lgalfaso** [comment]
I am trying to understand the issue here. Angular has a built-in locale that is loaded when you start your app and you did not load any locale before. This is, if you did not include any of the locale files before your app starts. Think of this like a fallback locale in case something fails.
Now, when you set an invalid locale as the default, the library tries to load it when it starts. If it fails, then generates an error. This is, the sequence is the following

* Angular starts, there is no locale loaded, then it uses 'en-us'
* This library starts, checks that there is a default and tries to load it
* Loading fails, generates an error event


If you would like to change the 'fallback' locale, then you should load a locale file in your app before your app starts.

I understand that this might be confusing, but there is no other option, we just do not know what other locale to load if the default fails.

**Comment by Olithom** [comment]
Ok, thank you, I thought that with defaultLocale('en-us') and localeLocationPattern('{{locale}}.js'), angular know the default file would be 'en-us.js'. Now I think I understood that fallback language can not be recovered with a xhr request but should be preloaded in angular. The problem is : 
 - I have a complex en-us file which set moment, angular-translate, etc... 
 - I cant change the source of angular.js.
 - I have this use case : a user can connect to a device that no longer has the language after log on a machine that has.

Thank you for your time and now I will search for the best way for my case.

**Comment by lgalfaso** [comment]
One solution would be to also include your en-us file. ei.
>
>   <script src="angular.js"><\script>
<script src="your-en-us.js"><\script>

**Comment by Olithom** [comment]
Hi, 

I have found the good way for my problem, If you want, you can watch the plunker, cliking on the 'missing language simulation' and running.

Thank for your help, the issue is closable.

**Comment by lgalfaso** [comment]
Good that this worked for you!
