### ISSUE TITLE
Error 404 in minify gulp build

### ISSUE THREAD

**Issue by leandrolimasi** [lgalfaso/angular-dynamic-locale#80]
Hi, I'm get a error 404 for the command **"tmhDynamicLocaleProvider.localeLocationPattern"** in minify gulp build. When not minify it's work fine.

Exists any workarround for this?

this is a error:

    http://localhost:3000/angular/i18n/angular-locale_pt-br.js Failed to load resource: the server responded with a status of 404 (Not Found)

**Comment by lgalfaso** [comment]
@leandrolimasi would it be possible for you to create a plunker that shows this issue?

**Comment by leandrolimasi** [comment]
@lgalfaso the problem is present in a config file from this project:

http://gitlab.cast.com.br/powerlogic/jcompany-view/blob/master/src/core/plc.config.js

the plunker is a project run in a command "**gulp serve:dist**" from a yoman gulp angular generator.
http://gitlab.cast.com.br/powerlogic/jcompany/tree/master/rhdemo-spa

the command run project in a minify configs. when not minify command "**gulp serve**", works fine.

the workaround sets up an online locale file, but i need a offline locale file in this way:

    
    tmhDynamicLocaleProvider.localeLocationPattern('bower_components/angular-i18n/angular-locale_{{locale}}.js');

**Comment by lgalfaso** [comment]
I think I am misreading something, as the two issues look different. This issue is saying that the minified version of this library is not working, this would be a big issue but I was unable to reproduce the problem. On the other side, the project claims that there is no way to preload the locales so this library would not need to load them dynamically. This is true, there is no built-in automatic mechanism to preload the locales. I am sure that this can be done without any modification to the library as the storage that this library uses is exposed. What is not present is a way to automatically extract the locale files for a list of locales and pre-populate the storage with these locales. The main issue here would be that there is no standard way to extract the locale from angular locale files.

That said, if we are talking about a small number of locales, then it should be possible to do so manually.

**Comment by RopoMen** [comment]
I think that this has something to do with $sce + [$interpolate](https://docs.angularjs.org/api/ng/service/$interpolate)

What happens if you add?

```js
.config(function($sceDelegateProvider) {
    var whiteList = $sceDelegateProvider.resourceUrlWhitelist();
    whiteList.push('*://code.angularjs.org./1.1.5/i18n/**');

    $sceDelegateProvider.resourceUrlWhitelist(whiteList);
})
```

**Comment by Cyber1000** [comment]
Did you find a solution (beside including external resources)? I need this too, we use minify for our whole project.
Thanks,
Cyber1000

**Comment by RopoMen** [comment]
I couldn't find any problem with minification. I use Gulp and usemin

and this is my configuration
```js
tmhDynamicLocaleProvider.localeLocationPattern('/static/dist/js/angular-locale_{{locale}}.js');
```

Only thing that I noticed is that you use "" instead of ''

**Comment by senthanal** [comment]
Hi, I have the same issue described by @leandrolimasi. In my production version, I have only 2 files. One for my own app script and the other one is vendor script. The vendor script contains all the third party libraries which are concatenated and minified. So, again, 'bower_components/angular-i18n/angular-locale_{{locale}}.js' doesn't valid anymore. Don't know how to solve this issue. Any help would be great. Thanks.

**Comment by lgalfaso** [comment]
from this thread, I think it is clear that there is a need for a tool that would:
* download a specific list of locale files (source location to be defined)
* repackage them into a module that would pre-populate this library storage

Then, the new module should be included as part of an existing library.

I think that building this tool should be strait-forward, and a PR is welcome.

**Comment by lgalfaso** [comment]
With 0.1.32, it is possible to pre-load resources in a build step as in https://github.com/lgalfaso/angular-dynamic-locale/issues/93#issuecomment-210826808
With this, this issue can be closed.
